[project]
name = "chirper"
version = "1.0.0"
description = "A web app that allows users to post messages and replies."
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "django>=5.1.6",
    "django-allauth>=65.4.0",
]
