# Generated by Django 5.1.6 on 2025-03-03 21:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Chirp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chirp_name', models.CharField(max_length=255)),
                ('time_created', models.DateTimeField(verbose_name='date published')),
                ('chirp_body', models.TextField()),
                ('parent_chirp_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='chirper.chirp')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
