# Generated by Django 5.1.6 on 2025-03-03 23:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chirper', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chirp',
            name='parent_chirp_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='chirper.chirp'),
        ),
    ]
