# Generated by Django 5.1.6 on 2025-03-04 23:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chirper', '0004_alter_like_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='chirp',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='chirper.chirp'),
        ),
    ]
