# Generated by Django 5.1.6 on 2025-03-05 20:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chirper', '0005_alter_like_chirp'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='chirp',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chirper.chirp'),
        ),
        migrations.AlterUniqueTogether(
            name='like',
            unique_together={('user', 'chirp')},
        ),
    ]
