# Generated by Django 5.1.6 on 2025-03-06 19:32

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chirper', '0006_alter_like_chirp_alter_like_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chirp',
            name='parent_chirp_id',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='chirper.chirp'),
        ),
        migrations.AlterField(
            model_name='chirp',
            name='time_created',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date published'),
        ),
    ]
